### ISSUE TITLE
How to use it from Windows Forms or other non web projects?

### ISSUE THREAD

**Issue by energywave** [lucapisano/GreenPassValidator#1]
Hello Luca, thank you so much for the work in this repo, that's very useful as I'm investigating (like you) how to decode the italian DGC.
I'm trying, however, to use it from a Windows Forms .net 5 project but I'm stuck as the constructor needs a IServiceProvider object. How to use it in a non web projects?
I'm not used to .net core so maybe that's a silly question, please forgive me in that case, just give me a hint.

Thank you in advance for your time.

**Comment by lucapisano** [comment]
Hi @energywave ,
To accomplish your requirement you might do the following:

using Microsoft.Extensions.DependencyInjection;
var sc = new ServiceCollection();
sc.AddGreenPassValidator();
var sp = sc.BuildServiceProvider();
var res = await _sp.GetRequiredService<ValidationService>().Validate("....");

Please see the test project for a working implementation that can be used in non web projects
P.s. you'll need the Nuget package Microsoft.Extensions.DependencyInjection
