### ISSUE TITLE
problem in ValidationService

### ISSUE THREAD

**Issue by x-etienne** [lucapisano/GreenPassValidator#2]
Hi Luca, 
I found a mistake in "ValidationService" at row 96 and 101, when you add "day" not "hours"

and at row 143 where you test "Certificate Valid Until" with "current date"

It is right? Or not?

thanks

**Comment by lucapisano** [comment]
Thank you for the feedback.Concerning the italian business rules, it's right to consider the value as Days, not hours.If you have other evidence for other European authorities, please let me know.Thank youCertified Multi Cloud ArchitectIl 21 set 2021 12:28, szcentropaghe ***@***.***> ha scritto:
Hi Luca,
I found a mistake in "ValidationService" at row 96 and 101, when you add "day" not "hours"
It is right? Or not?
thanks

**Comment by lucapisano** [comment]
Thank you, I agree with you for lines 96 and 101 because the rule engine returns a value in Hours. It is a bug and I'm gonna correct it

I do not agree for line 143 because it is comparing DateTime objects

**Comment by x-etienne** [comment]
You are welcome!

> I do not agree for line 143 because it is comparing DateTime objects

Yes, you are right! I saw now that you have commit a fix yesterday "fix recoveries date"

Another doubt that I see in the code... At line 32 of CachingService. That condition is true only first time, when it download the rules from web... but after not

And for last... Would be possible to put the project to ".NET Standard 2.0"? I would like to use in my aspx project and ".NET Standard 2.1" in this case is not avaible (https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.1.md)

thanks again!

**Comment by lucapisano** [comment]
Hi @szcentropaghe ,
Last 2 commits address those issues. Thank you for feedback
