### ISSUE TITLE
Couldn't download rules because of "Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'."

### ISSUE THREAD

**Issue by simoneluconi** [lucapisano/GreenPassValidator#5]
Hi, i tried the example but i couldn't get my certificate validated because the rules don't get downloaded with the error in the title.
I read online that the issue could be that the ciphers of my OS are not supported anymore and to update my os. 
But i don't know what to update to because i tried with Windows 11 21H2 and Windows Server 2019 1809. Am i missing something? 

With chrome or postman a have no problem getting the data from https://get.dgc.gov.it/v1/dgc/settings

Thanks.

**Comment by lucapisano** [comment]
I confirm this setting is inhereted from the OS.
Please ensure that you've enabled TLS 1.3 or TLS 1.2 in the Internet Explorer options, Advanced Tab.
https://www.cdn77.com/tls-test/result?domain=https://get.dgc.gov.it/v1/dgc/settings

Please feel free to re-open the issue in case is needed

**Comment by simoneluconi** [comment]
I alredy checked, they are enabled:
![1](https://user-images.githubusercontent.com/12747695/137367828-98f0743b-187e-40a6-8a1a-8b634aff9c08.png)

![2](https://user-images.githubusercontent.com/12747695/137368015-27db7861-1224-4b23-a4f8-6010a845989a.png)

**Comment by simoneluconi** [comment]
Adding the line 
 `ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;`
in the constructor seems to fix the issue 🤔

```
public ValidationService(CertificateManager certificateManager, IServiceProvider sp)
        {
            _certManager = certificateManager;
            _sp = sp;
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
        }
```
