### ISSUE TITLE
How I use it

### ISSUE THREAD

**Issue by ELIA1233** [lucapisano/GreenPassValidator#7]
Hi, I ask how i use it and in README.md add how to use 

Good job!

**Comment by extremerz89** [comment]
fra, nel caso in cui io ti dessi le chiavi, mi aiuteresti?

**Comment by ELIA1233** [comment]
Non so programmare però era solo per sapere

**Comment by lucapisano** [comment]
@ELIA1233 ciao, nel readme ci sono le istruzioni per usarlo, appena sotto le feature. È necessario saper programmare in .NET e sapere il paradigma DependencyInjection.

Altrimenti c'è una demo funzionante linkata nel readme
https://greenpassapi.azurewebsites.net/
