### ISSUE TITLE
Super-greenpass

### ISSUE THREAD

**Issue by Schtailian** [lucapisano/GreenPassValidator#9]
Hi,
if you are interested and if this is still alive i would implement the super-greenpass.

I was thinking of adding the fields IsVaccinated, IsRecovered, IsTested to the return from the `.Validate()` method. That way every application can decide by itself what's necessary for them.

Let me know what you think.

**Comment by Mrizzi-96** [comment]
Hi Schtailian,
I am currently implementing all the new validation types, following the new Italian specifications, and I am in the middle of testing everything to make sure it was implemented correctly.
Once the testing phase finishes I will be submitting a pull request to Luca to integrate the new modifications.
Best regards,
Marco.

**Comment by Schtailian** [comment]
Hi Marco,
sounds awesome.
I'll close this issue, let me know when you need some help.

**Comment by lucapisano** [comment]
Thank you very much, I'll be glad to review the PR
